#!/usr/bin/env python

import sys

if len(sys.argv) != 2:
    print 'pass one argument, the string to attempt to "import" in python'

module = sys.argv[1]
code = '''
import %(module)s
'''

try:
    exec code % globals()
    print 'sucessfully imported %(module)s' % globals()
except Exception, ex:
    print ex
    print 'failed to import %(module)s' % globals()
